keys:
  - &mac age1ad9fjt5q47jz7gqdar2vg7u769a7s0vgln3d3st8jedh2hmmlenqqn896w
  - &recovery age1uuc265dsjsumul0lgrsvslwjpgmav3wqsk3u33jq28j7hrvuygfqc0d2ay

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
        - *mac
        - *recovery
